$(shell mkdir -p rootfsimg/build)

APPS = hello_xsai after_workload gemm_precomp busybox before_workload llama.cpp pmu_test
# trap qemu_trap dtc lkvm-static

APPS_DIR = $(addprefix apps/, $(APPS))

XSAI_INIT_MODE ?= manual
ifeq ($(XSAI_INIT_MODE),ci)
XSAI_WORKLOAD ?= llama-fake-bench-suite
XSAI_AUTO_EXIT ?= 1
XSAI_DROP_SHELL ?= 0
else
ifeq ($(XSAI_INIT_MODE),shell)
XSAI_WORKLOAD ?= none
XSAI_AUTO_EXIT ?= 0
XSAI_DROP_SHELL ?= 1
else
XSAI_WORKLOAD ?= llama-fake-bench-suite
XSAI_AUTO_EXIT ?= 0
XSAI_DROP_SHELL ?= 1
endif
endif
XSAI_RUN_AFTER_WORKLOAD ?= 1
XSAI_DUMP_THP ?= 1
XSAI_TRACE_WORKLOAD ?= 1
XSAI_GGML_AME_LOG ?= 0
XSAI_GGML_AME_PACKED_Q8 ?= 1

.PHONY: rootfsimg xsai-init-config $(APPS_DIR) clean

rootfsimg: xsai-init-config $(APPS_DIR)

xsai-init-config:
	@mkdir -p rootfsimg/build
	@{ \
	  echo "# Generated by firmware/riscv-rootfs/Makefile"; \
	  printf "XSAI_MODE='%s'\n" "$(XSAI_INIT_MODE)"; \
	  printf "WORKLOAD='%s'\n" "$(XSAI_WORKLOAD)"; \
	  printf "AUTO_EXIT='%s'\n" "$(XSAI_AUTO_EXIT)"; \
	  printf "DROP_SHELL='%s'\n" "$(XSAI_DROP_SHELL)"; \
	  printf "RUN_AFTER_WORKLOAD='%s'\n" "$(XSAI_RUN_AFTER_WORKLOAD)"; \
	  printf "DUMP_THP='%s'\n" "$(XSAI_DUMP_THP)"; \
	  printf "TRACE_WORKLOAD='%s'\n" "$(XSAI_TRACE_WORKLOAD)"; \
	  printf "GGML_AME_LOG='%s'\n" "$(XSAI_GGML_AME_LOG)"; \
	  printf "GGML_AME_PACKED_Q8='%s'\n" "$(XSAI_GGML_AME_PACKED_Q8)"; \
	} > rootfsimg/build/xsai-init.conf

$(APPS_DIR): %:
	@echo "$$(date '+[rootfs %F %T %z] START $@')"
	@$(MAKE) -s -C $@ install
	@echo "$$(date '+[rootfs %F %T %z] END $@')"

clean:
	-$(foreach app, $(APPS_DIR), $(MAKE) -s -C $(app) clean ;)
	-rm -f rootfsimg/build/*

distclean:
	-$(foreach app, $(APPS_DIR), $(MAKE) -s -C $(app) distclean ;)
	-rm -f rootfsimg/build/*
	-rm -rf apps/busybox/repo
	-rm -rf apps/llama.cpp/repo
