#!/bin/sh

pwd
ls
echo 12345
ifconfig lo 127.0.0.1
/root/redis/redis-server /root/redis/redis.conf
sleep 1
ps -a
netstat -apnt
ifconfig
cat /root/redis/warmup-redis.cmd | /root/redis/redis-cli --pipe
/root/new_before_workload
cat /root/redis/run-redis.cmd | /root/redis/redis-cli --pipe
/root/after_workload
