NAME = linux

include $(RISCV_ROOTFS_HOME)/Makefile.app
include $(RISCV_ROOTFS_HOME)/Makefile.get

URL = https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.13.tar.xz

.PHONY: $(APP)
$(APP): | unpack

